### ISSUE TITLE
Update the poplar model app for Daymet operation

### ISSUE THREAD

**Issue by qjhart** [CSTARS/poplar-model-app#3]
@hitchpy has identified that [daymet](http://daymet.ornl.gov/web_services.html) is probably the best tool for getting single pixel weather data for the entire country.  This is at an even better 1km resolution, with the bonus of including Rs data directly.  

We should consider adding some selector methodology, for different weather inputs.  Daymet may be a complete replacement for our current inputs.  In the case of looking into the future, we could do something like automatically download 5 years of data, and create average on the fly.  Note the API is so coarse that that wouldn't be more a hardship than using the data itself.

**Comment by jrmerz** [comment]
I inspected to the API, it's a solid D for web access :/. They have two options, one downloads data as CSV with Content-Disposition: attachment in the HTTP header.  The 'browser' version dumps a web page with an HTML table of the data.  Page is complete with analytics scripts and all.  Neither are CORS enabled, so we will have to setup a server side script to pull data on the fly.  I would recommend the CSV version in this case.

Just a reminder, the current model app is all web service based in it's interactions, the app itself is simply served from apache as a static page.  We do host a visualization source on alder (alder.bioenergy.casil.ucdavis.edu/vizsource) for average weather and soil data access.

With that said, @qjhart how would you like to proceed?

**Comment by qjhart** [comment]
How about a small A+ web access proxy from the same server that hosts the viz source?

**Comment by jrmerz** [comment]
We can.  Just something else we have to maintain, and make sure we secure, so we are not opening up a world wide proxy.

**Comment by qjhart** [comment]
In the long run, maybe easier than maintaining our static database.

**Comment by jrmerz** [comment]
we now have this code here: https://github.com/CSTARS/pg-poplar-3pg-model/blob/master/plpy.sql
Closing issue since it's no longer related to this repo.
